config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get    "tasks",           to: "tasks#index"
  get    "tasks/new",       to: "tasks#new"
  post   "tasks",           to: "tasks#create"
  get    "tasks/:id",       to: "tasks#show", as: :task
  get    "tasks/:id/edit",  to: "tasks#edit", as: :tasks_edit
  patch  "tasks/:id",       to: "tasks#update"
  delete "tasks/:id",       to: "tasks#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, :details, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params.require(:task).permit(:title, :details, :completed))
    @task.save
    redirect_to(tasks_path)
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(params.require(:task).permit(:title, :details, :completed))
    redirect_to(task_path)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to(tasks_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/index.html.erb
<% @tasks.each do |task| %>
  <h2> <%= link_to task.title, task_path(task) %> </h2>
  <input type="checkbox" name="task" value="" disabled <%= 'checked' if task.completed %>> Completed [✓] <br>
  <%= link_to "Delete", task_path(task),
    method: :delete,
    data: { confirm: "Are you sure?" }
  %>
  <hr>
<% end %>

<p> <%= link_to "Add a new task", tasks_new_path %> <p>

app/views/tasks/new.html.erb
<div id="container">
  <%= form_for(@task) do |f| %>
  <div class="form-row">
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
  </div>

  <div class="form-row">
    <div class="form-group">
      <%= f.label :details %>
      <%= f.text_field :details, class: 'form-control' %>
    </div>
  </div>

    <%= f.submit class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<!-- app/views/tasks/show.html.erb -->
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p> <%= link_to "Back to list", tasks_path %> </p>

<p><%= link_to "Edit this task", tasks_edit_path %> </p>